# Generated by Django 4.1.7 on 2025-09-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_logindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='resetpassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_password', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
