# Generated by Django 4.1.7 on 2025-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_resetpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiledata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact_number', models.IntegerField()),
                ('Nationality', models.CharField(max_length=200)),
                ('Pincode', models.IntegerField()),
                ('password', models.IntegerField()),
            ],
        ),
    ]
