# Generated by Django 4.1.7 on 2025-09-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_profiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='correctpassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('repassword', models.IntegerField()),
            ],
        ),
    ]
