# Generated by Django 4.1.7 on 2025-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_correctpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilepicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
