# Generated by Django 4.1.7 on 2025-09-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile_pic',
            field=models.ImageField(upload_to='profilepics/'),
        ),
    ]
