# Generated by Django 4.1.7 on 2025-09-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_profilepicture_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='postitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=5000)),
                ('postimage', models.ImageField(upload_to='postimages/')),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
    ]
