# Generated by Django 4.1.7 on 2025-09-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_postitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('content', models.TextField(max_length=2000)),
            ],
        ),
    ]
