# Generated by Django 4.1.7 on 2025-09-24 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_commentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdata',
            name='Postitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogapp.postitem'),
        ),
    ]
